### ISSUE TITLE
The tool doesn't work as excepted.

### ISSUE THREAD

**Issue by mismismo** [MCMrARM/obj-skin-studio#4]
The issue is when I import a geometry file (in a 1.10.0 format), it's open without any issue but doesn't show the cube model.

Even if I put the texture with the exact UV, it's doesn't show the model but the export is working well. Maybe cube doesn't appear when a 1.10.0 format or newest format is opened.

I tried to import a .OBJ file and nothing seem to be appear, I tried to clean cache like ManiacGamer156 issue on the Google Chrome Browser and nothing is fixed.

I tried on different browser like: Microsoft Edge (Chromnium Open Source) and Mozilla Firefox and still didn't fixed the issue.

I did tried opening a Polymesh model and the result is the same.

I didn't tried on a 1.8.0 format yet. Any help please? I don't exactly know how to import a .OBJ format.

**Comment by MCMrARM** [comment]
you can only import .obj (.json geometry is not supported), make sure the size is correct

**Comment by mismismo** [comment]
Oh okay, thank you!

It's doesn't work for some .OBJ .
